/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as TracksIndexRouteImport } from './routes/tracks.index'
import { Route as TracksSlugRouteImport } from './routes/tracks.$slug'
import { Route as TracksTerraformRouteImport } from './routes/tracks.terraform'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TracksRoute,
} as any)
const TracksSlugRoute = TracksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TracksRoute,
} as any)
const TracksTerraformRoute = TracksTerraformRouteImport.update({
  id: '/terraform',
  path: '/terraform',
  getParentRoute: () => TracksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/roadmap': typeof RoadmapRoute
  '/tracks': typeof TracksRouteWithChildren
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/terraform': typeof TracksTerraformRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/roadmap': typeof RoadmapRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/terraform': typeof TracksTerraformRoute
  '/tracks': typeof TracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/roadmap': typeof RoadmapRoute
  '/tracks': typeof TracksRouteWithChildren
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/terraform': typeof TracksTerraformRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/roadmap'
    | '/tracks'
    | '/tracks/$slug'
    | '/tracks/terraform'
    | '/tracks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/roadmap' | '/tracks/$slug' | '/tracks/terraform' | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/roadmap'
    | '/tracks'
    | '/tracks/$slug'
    | '/tracks/terraform'
    | '/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoadmapRoute: typeof RoadmapRoute
  TracksRoute: typeof TracksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof TracksRoute
    }
    '/tracks/$slug': {
      id: '/tracks/$slug'
      path: '/$slug'
      fullPath: '/tracks/$slug'
      preLoaderRoute: typeof TracksSlugRouteImport
      parentRoute: typeof TracksRoute
    }
    '/tracks/terraform': {
      id: '/tracks/terraform'
      path: '/terraform'
      fullPath: '/tracks/terraform'
      preLoaderRoute: typeof TracksTerraformRouteImport
      parentRoute: typeof TracksRoute
    }
  }
}

interface TracksRouteChildren {
  TracksSlugRoute: typeof TracksSlugRoute
  TracksTerraformRoute: typeof TracksTerraformRoute
  TracksIndexRoute: typeof TracksIndexRoute
}

const TracksRouteChildren: TracksRouteChildren = {
  TracksSlugRoute: TracksSlugRoute,
  TracksTerraformRoute: TracksTerraformRoute,
  TracksIndexRoute: TracksIndexRoute,
}

const TracksRouteWithChildren =
  TracksRoute._addFileChildren(TracksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoadmapRoute: RoadmapRoute,
  TracksRoute: TracksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
